version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: /cyberstreams
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
