name = "cyberstreams"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "cyberstreams-prod"
vars = { ENVIRONMENT = "production" }

[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_KV_ID"

[[d1_databases]]
binding = "DB"
database_name = "cyberstreams-db"
database_id = "YOUR_D1_DATABASE_ID"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "cyberstreams-storage"

[[vectorize]]
binding = "VECTORSTORE"
index_name = "cyberstreams-vectors"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[[routes]]
pattern = "cyberstreams.example.com/*"
zone_name = "example.com"

[observability]
enabled = true

[[analytics_engine_datasets]]
binding = "ANALYTICS"

[env.staging]
name = "cyberstreams-staging"
vars = { ENVIRONMENT = "staging" }

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "YOUR_STAGING_KV_ID"

[env.development]
name = "cyberstreams-dev"
vars = { ENVIRONMENT = "development" }
