import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Card } from '@components/Card';
import { Text } from '@components/Text';
import threatsData from '@data/threats.json';
const threats = threatsData;
export default function Intelligence() {
    return (_jsxs("div", { className: "stack", style: { display: 'grid', gap: '16px' }, children: [_jsxs(Card, { children: [_jsx(Text, { variant: "title", children: "Dark Web Ransomware Monitor" }), _jsx(Text, { children: "Nedenfor finder du en oversigt over de aktuelt sporede ransomware angreb. Listen er baseret p\u00E5 trusselsdata fra Dark Web Monitor og opdateres l\u00F8bende.  Du kan bruge denne sektion til at f\u00E5 et hurtigt overblik over alvor, m\u00E5l og angrebsgrupper." })] }), _jsx(Card, { style: { overflowX: 'auto' }, children: _jsxs("table", { style: { width: '100%', borderCollapse: 'collapse' }, children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { style: { textAlign: 'left', padding: '8px', borderBottom: '1px solid rgba(0,0,0,0.1)' }, children: "Offer" }), _jsx("th", { style: { textAlign: 'left', padding: '8px', borderBottom: '1px solid rgba(0,0,0,0.1)' }, children: "Gruppe" }), _jsx("th", { style: { textAlign: 'left', padding: '8px', borderBottom: '1px solid rgba(0,0,0,0.1)' }, children: "Severity" }), _jsx("th", { style: { textAlign: 'left', padding: '8px', borderBottom: '1px solid rgba(0,0,0,0.1)' }, children: "Land" }), _jsx("th", { style: { textAlign: 'left', padding: '8px', borderBottom: '1px solid rgba(0,0,0,0.1)' }, children: "Dato" }), _jsx("th", { style: { textAlign: 'left', padding: '8px', borderBottom: '1px solid rgba(0,0,0,0.1)' }, children: "Beskrivelse" })] }) }), _jsx("tbody", { children: threats.map(threat => (_jsxs("tr", { children: [_jsx("td", { style: { padding: '8px', verticalAlign: 'top' }, children: threat.victim_name }), _jsx("td", { style: { padding: '8px', verticalAlign: 'top' }, children: threat.group_name }), _jsx("td", { style: { padding: '8px', verticalAlign: 'top' }, children: threat.severity }), _jsx("td", { style: { padding: '8px', verticalAlign: 'top' }, children: threat.country }), _jsx("td", { style: { padding: '8px', verticalAlign: 'top' }, children: threat.discovered_date }), _jsx("td", { style: { padding: '8px', verticalAlign: 'top' }, children: threat.description })] }, threat.id))) })] }) })] }));
}
