name = "cyberstreams"
compatibility_date = "2025-10-12"
pages_build_output_dir = "./dist"

[env.production]
name = "cyberstreams-prod"

[[env.production.vars]]
DEPLOY_ENV = "production"
VECTOR_DB_PATH = "vector_db.pkl"
