name: Osint Catalog Sync

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r osint/requirements.txt

      - name: Hydrate OSINT catalog
        run: |
          python -m osint.ingestors.awesome_osint_parser

      - name: Run OSINT unit tests
        run: |
          python -m pytest osint/tests

      - name: Detect drift
        run: |
          git status --short
          git diff --stat
