name: Deploy to Railway

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli@latest

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "Checking Railway project status..."
          railway status || true
          echo "---"
          echo "Checking available services..."
          railway service || true
          echo "---"
          echo "Attempting to link and deploy..."
          railway link incredible-heart || true
          railway up --detach
