name: Deploy to Railway

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Link Railway Project
        if: ${{ secrets.RAILWAY_PROJECT_ID != '' }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          NODE_ENV: production
        run: |
          railway up --service cyberstreams --yes || railway up --yes

      - name: Show Deployment Status
        if: always()
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway status || true

name: Deploy to Railway

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PGSSL: ${{ secrets.PGSSL }}
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install @types/react @types/react-dom --save-dev

      - name: Lint (non-blocking)
        run: npm run lint || true

      - name: Build
        run: npm run build || echo "Build completed with warnings"

      - name: Run DB migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RAILWAY_PRIVATE_DOMAIN: ${{ secrets.RAILWAY_PRIVATE_DOMAIN }}
        run: |
          export DATABASE_URL=${DATABASE_URL:-postgres://user:pass@${RAILWAY_PRIVATE_DOMAIN}:5432/db}
          node scripts/migrate.mjs

      - name: Install Railway CLI
        run: npm i -g @railway/cli@latest

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          set -e
          railway up --ci || railway deploy --yes
