name: Deploy to Railway (Optional)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-secrets:
    name: Check Railway Secrets
    runs-on: ubuntu-latest
    outputs:
      secrets-available: ${{ steps.check.outputs.available }}
    steps:
      - name: Check if Railway secrets are configured
        id: check
        run: |
          if [ -n "${{ secrets.RAILWAY_TOKEN }}" ] && [ -n "${{ secrets.RAILWAY_PROJECT_ID }}" ] && [ -n "${{ secrets.RAILWAY_SERVICE_ID }}" ]; then
            echo "available=true" >> $GITHUB_OUTPUT
            echo "✅ Railway secrets are configured"
          else
            echo "available=false" >> $GITHUB_OUTPUT
            echo "ℹ️ Railway secrets not configured - deployment skipped"
          fi

  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: check-secrets
    if: needs.check-secrets.outputs.secrets-available == 'true'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Install Railway CLI
        run: npm install -g @railway/cli@4

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_ENVIRONMENT: ${{ secrets.RAILWAY_ENVIRONMENT }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
        run: |
          set -euo pipefail

          if [ -z "${RAILWAY_TOKEN:-}" ]; then
            echo "RAILWAY_TOKEN secret is required to deploy" >&2
            exit 1
          fi

          railway login --token "$RAILWAY_TOKEN"

          if [ -z "${RAILWAY_PROJECT_ID:-}" ]; then
            echo "RAILWAY_PROJECT_ID secret is required to link the GitHub workflow" >&2
            exit 1
          fi

          if [ -z "${RAILWAY_SERVICE_ID:-}" ]; then
            echo "RAILWAY_SERVICE_ID secret is required to target the correct service" >&2
            exit 1
          fi

          railway link --project "$RAILWAY_PROJECT_ID"

          if [ -n "${RAILWAY_ENVIRONMENT:-}" ]; then
            export RAILWAY_ENVIRONMENT
            railway use environment "$RAILWAY_ENVIRONMENT" \
              || railway use --environment "$RAILWAY_ENVIRONMENT" \
              || echo "Warning: unable to pre-select environment, relying on CLI defaults"
          fi

          railway up --ci --build --wait --no-confirm --service "$RAILWAY_SERVICE_ID"
