name: Deploy to Railway

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Railway via GitHub Integration
        run: |
          echo "✅ Code pushed to GitHub"
          echo ""
          echo "🚂 Railway will auto-deploy if GitHub integration is configured"
          echo ""
          echo "📋 To set up Railway GitHub integration:"
          echo "1. Go to https://railway.app/project/incredible-heart"
          echo "2. Click on a service (or create new service)"
          echo "3. Go to Settings → Connect to GitHub"
          echo "4. Select repository: Clauskraft/cyberstreams"
          echo "5. Railway will automatically deploy on every push to master"
          echo ""
          echo "Alternative: Add RAILWAY_SERVICE_NAME as GitHub secret"
          echo "Then this workflow can use: railway up --service \$RAILWAY_SERVICE_NAME"
